// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rxrggbYaRCTRl81bbpB7bbMtmD-RIiU',
    appId: '1:876994628515:web:e5d38db3e508452e0be816',
    messagingSenderId: '876994628515',
    projectId: 'parsley-auth',
    authDomain: 'parsley-auth.firebaseapp.com',
    storageBucket: 'parsley-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgiIOa1RdbaMU31aQCAtlMpg24SJMNVOI',
    appId: '1:876994628515:android:13a49ee5d02f22c10be816',
    messagingSenderId: '876994628515',
    projectId: 'parsley-auth',
    storageBucket: 'parsley-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGr4fcAxBDBIOZ9N-LgZV50rtokoNDEMs',
    appId: '1:876994628515:ios:4232736a0f01569a0be816',
    messagingSenderId: '876994628515',
    projectId: 'parsley-auth',
    storageBucket: 'parsley-auth.appspot.com',
    androidClientId: '876994628515-bq9ks2f4gs5u8jhrqei5cs3unlphnjrl.apps.googleusercontent.com',
    iosClientId: '876994628515-3h5p4n6npr7l7iflffc1feok0cnj4hhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.parsley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGr4fcAxBDBIOZ9N-LgZV50rtokoNDEMs',
    appId: '1:876994628515:ios:4232736a0f01569a0be816',
    messagingSenderId: '876994628515',
    projectId: 'parsley-auth',
    storageBucket: 'parsley-auth.appspot.com',
    androidClientId: '876994628515-bq9ks2f4gs5u8jhrqei5cs3unlphnjrl.apps.googleusercontent.com',
    iosClientId: '876994628515-3h5p4n6npr7l7iflffc1feok0cnj4hhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.parsley',
  );
}
